/**
 * known_vendors.ts - List of known headphone vendors
 *
 * This module contains the canonical list of headphone/IEM vendors.
 * Used for parsing product names without requiring external API calls.
 *
 * The list is sorted by length (longest first) for greedy matching,
 * so "Audio Technica" matches before "Audio".
 */

/**
 * List of known headphone vendors.
 *
 * Guidelines for adding vendors:
 * - Use the most common spelling/capitalization
 * - Include alternate spellings if needed (e.g., "B&W", "Bowers & Wilkins")
 * - Multi-word vendors should come before single words (handled by sort)
 * - Don't include "Audio" or "Sound" alone - too generic
 */
export const KNOWN_VENDORS = [
  // Multi-word vendors (4+ words)
  "Rosson Audio Design",
  "House Of Marley",
  "Advanced AcousticWerkes",
  "Soul by Ludacris",
  "Alpha & Delta",
  "Alpha Design Labs",
  "Etymotic Research",
  "AFUL Acoustics",
  "Shuoer Aoshida",
  "Creative Labs",

  // Multi-word vendors (3 words)
  "Dan Clark Audio",
  "Modhouse Audio",
  "Andover Audio",
  "Astro Gaming",
  "Sivga Audio",
  "Acoustic Research",
  "Ambient Acoustics",
  "Ambient Dynamics",
  "Light Harmonic",
  "Master & Dynamic",
  "Master Dynamic",

  // Multi-word vendors (2 words)
  "Adam Audio",
  "Base Audio",
  "KB EAR",
  "Kaldas Research",
  "Lily Audio",
  "64 Audio",
  "Astell & Kern",
  "Audio Genetic",
  "Audio Technica",
  "Audio-Technica",
  "Audio Zenith",
  "Austrian Audio",
  "Bowers & Wilkins",
  "Bowers Wilkins",
  "Cambridge Audio",
  "Campfire Audio",
  "Cooler Master",
  "Cosmic Ears",
  "Dan Clark",
  "Empire Ears",
  "Final Audio",
  "Flare Audio",
  "Gold Planar",
  "Harman Kardon",
  "JH Audio",
  "Kiwi Ears",
  "LZ Audio",
  "Mark Levinson",
  "Mee Audio",
  "Noble Audio",
  "NS Audio",
  "Periodic Audio",
  "Rosson Audio",
  "Sendy Audio",
  "Slate Audio",
  "Sound Intone",
  "Spiral Ear",
  "Status Audio",
  "Tin Audio",
  "Tin HiFi",
  "Ultimate Ears",
  "Unique Melody",
  "V Moda",
  "V-MODA",
  "Vision Ears",
  "Warwick Acoustics",
  "Warwick Audio",
  "IMR Acoustics",
  "Simgot Audio",

  // Multi-word vendors found in AutoEQ
  "7th Acoustics",
  "A-Audio",
  "Accidentally Extraordinary",
  "Aroma Audio",
  "ASUS ROG",
  "Atomic Floyd",
  "Auribus Acoustics",
  "AüR Audio",
  "Dark Project",
  "ELISE AUDIO",
  "Grell Audio",
  "Hi-Fri Audio",
  "Howard Leight",
  "Music Hall Audio",
  "Under Armour",
  "Unknown Custom",
  "Big Bus",
  "Delta Air",
  "DMS Project",
  "ES Lab",
  "Silver Monkey",
  "Singapore Airlines",
  "Enigmatic Audio",
  "ENIGMAcoustics",
  "Eternal Melody",
  "Fosi Audio",
  "Focus Audio",
  "nb Audio",
  "Pump Audio",
  "PureSound",
  "Signature Acoustics",
  "Sound Linear",
  "Steven Slate Audio",
  "TAGO STUDIO",
  "TXN Audio",
  "Alpha Omega",
  "Anthem Five",
  "Bamboo Forest",
  "Bang & Olufsen",
  "Binary Acoustics",
  "California Headphone Company",
  "Canal Works",
  "Cat Ear Audio",
  "Craft Ears",
  "Custom Art",
  "Dark Legend",
  "Effect Audio",
  "Geek Wold",
  "GS Audio",
  "MYER-AUDIO",
  "Sound Rhyme",
  "Turtle Beach",
  "Tansio Mirai",
  "Dita Audio",
  "FAudio",
  "Fearless Audio",
  "First Harmonic",
  "Fischer Audio",
  "FLC Technology",
  "Flicker Ear",
  "Heir Audio",
  "HiFi Boy",
  "HIFI FOR ALL",
  "Ice Lab",
  "IO Audio",
  "ISN Audio",
  "ISN AUDIO",
  "Itsfit Lab",
  "Jade Audio",
  "JLab Audio",
  "JM Audio",
  "Jomo Audio",
  "JQ Audio",
  "Just Ear",
  "Kumitate Lab",
  "Lear",
  "LH Labs",
  "Life Acoustics",
  "Lime Ears",
  "Little Dot",
  "LZ Hi-Fi Audio",
  "Mangird",
  "Mayflower Electronics",
  "Meizu",
  "Metal Magic Research",
  "Meyer Audio",
  "MiM Audio",
  "Moe Audio",
  "NF ACOUS",
  "NF Audio",
  "Night Oblivion",
  "NocturnaL Audio",
  "Nostalgia Audio",
  "NXEars",
  "Ocharaku",
  "OneOdio",
  "OnePlus",
  "Open Audio",
  "OpenAudio",
  "Origami Audio",
  "Pai Audio",
  "Peacock Audio",
  "Plus Sound",
  "PlusSound",
  "PMG Audio",
  "Polk Audio",
  "Prisma Audio",
  "Punch Audio",
  "Queen of Audio",
  "Rose Technics",
  "See Audio",
  "SeeAudio",
  "Shortbus Audio",
  "SoundPeats",
  "Symphonium Audio",
  "Tangzu",
  "TANGZU",
  "Venture Electronics",
  "Wiss Audio",
  "XK-Audio",
  "Xenns",
  "Yanyin",
  "YU9 Audio",
  "Zero Audio",

  // Single-word vendors (sorted alphabetically for maintainability)
  "MOFI",
  "Zaylli",
  "1Custom",
  "1More",
  "634ears",
  "7Hz",
  "AAW",
  "Abyss",
  "ACEFAST",
  "Acoustune",
  "Adam",
  "Advanced",
  "Aedle",
  "AFUL",
  "ARTTI",
  "Audient",
  "Audiosense",
  "AUKEY",
  "Aure",
  "Aurisonics",
  "Avantree",
  "AVIOT",
  "Aya",
  "AZLA",
  "AuGlamour",
  "AudioFly",
  "AfterShokz",
  "Baseus",
  "BASN",
  "Betron",
  "BKHC",
  "Bloc",
  "Blue",
  "BlueAnt",
  "Bluedio",
  "BlueParrott",
  "Boltune",
  "Boqari",
  "BÖHM",
  "Caeden",
  "Canpur",
  "Cardas",
  "CAT",
  "Cayin",
  "CCZ",
  "CHIKYU-SEKAI",
  "CKLVX",
  "Clariar",
  "Clear",
  "CMF",
  "Co-Donguri",
  "Colorfly",
  "Corsair",
  "Cougar",
  "Comradz",
  "Cowin",
  "Cozoy",
  "CrinEar",
  "Cyberdrive",
  "Cypher",
  "Defunc",
  "Dolby",
  "Dynamic Motion",
  "Agasound",
  "AIAIAI",
  "Aiderlot",
  "Akai",
  "AKG",
  "Alclair",
  "AME",
  "Akoustyx",
  "Altec",
  "Altiat",
  "Anew",
  "AOSHIDA",
  "Apevoix",
  "ARC",
  "Allen & Heath",
  "Amazon",
  "Andover",
  "Anker",
  "Apple",
  "Arpegear",
  "Astro",
  "Audeze",
  "Audioquest",
  "Aune",
  "Aurorus",
  "Avantone",
  "Fairphone",
  "FAAEAL",
  "Fengru",
  "Fifine",
  "FIIL",
  "fineEars",
  "fix",
  "Floaudio",
  "Fonge",
  "Fujisan",
  "Fitbit",
  "FitEar",
  "FlipEars",
  "B&O",
  "B&W",
  "Beats",
  "Behringer",
  "Benchmark",
  "Beyerdynamic",
  "BGVP",
  "BLON",
  "Blon",
  "Bose",
  "BQEYZ",
  "Brainwavz",
  "Campfire",
  "CCA",
  "Cleer",
  "Coolermaster",
  "Creative",
  "CVJ",
  "Dali",
  "Dita",
  "Daiso",
  "Darkvoice",
  "DCMEKA",
  "Debauche",
  "Denon",
  "Dethonray",
  "Devialet",
  "Diskin",
  "DubsLabs",
  "Drop",
  "Dunu",
  "Dyson",
  "ddHiFi",
  "E-MU",
  "EarFun",
  "Earfun",
  "EarSonics",
  "EarAcoustic",
  "Eartech",
  "EarWerkz",
  "ECCI",
  "ENACFIRE",
  "Endorfy",
  "Eskuche",
  "Echobox",
  "écoute",
  "Edifier",
  "EKSA",
  "EPOS",
  "Elysian",
  "Emotiva",
  "EPZ",
  "ETA",
  "Etimova",
  "Etymotic",
  "Fatfreq",
  "Euclid",
  "Fender",
  "Fenhou",
  "Fidue",
  "FiiO",
  "Fir Audio",
  "Focal",
  "Focusrite",
  "Fostex",
  "Future",
  "Gaudio",
  "Geekfly",
  "Genesis",
  "GK",
  "Google",
  "Grado",
  "Grell",
  "GuideRay",
  "Graphene",
  "HAKUGEI",
  "HarmonicDyne",
  "Havi",
  "Haylou",
  "HeartField",
  "Heavys",
  "HEDD",
  "Hessian",
  "HiBy",
  "Hidition",
  "Hidizs",
  "HiFiMAN",
  "Hifiman",
  "Hisenior",
  "HiSoundAudio",
  "Horluchs",
  "HUM",
  "Huawei",
  "Hyla",
  "HyperX",
  "HZSOUND",
  "iBasso",
  "Ikko",
  "IMR",
  "INAIR",
  "InAwaken",
  "InEar",
  "I-INTO",
  "I-Mego",
  "iClever",
  "iHarmonix",
  "iKF",
  "iMetal",
  "Insignia",
  "INTUAURA",
  "Intime",
  "iSK",
  "ivipQ",
  "Ivery",
  "Jabra",
  "Jaybird",
  "JAYS",
  "JBL",
  "JCally",
  "Jialai",
  "JLab",
  "Joyodio",
  "JQ",
  "Juzear",
  "JVC",
  "Kaiku",
  "KBEAR",
  "KEF",
  "KEFINE",
  "Kennerton",
  "KFA2",
  "KiiBOOM",
  "KingSound",
  "Kinera",
  "Kitsound",
  "KLH",
  "Klipsch",
  "Kojo",
  "Kontinum",
  "Koss",
  "Ks",
  "Kotori",
  "KRK",
  "KZ",
  "Lafitear",
  "LAMAX",
  "Lark",
  "Lenntek",
  "Lenovo",
  "Letshuoer",
  "LG",
  "Libratone",
  "Lindy",
  "Linsoul",
  "Lioncast",
  "Logitech",
  "LucidSound",
  "Ludos",
  "Lypertek",
  "Mackie",
  "Madoo",
  "Magaosi",
  "Marshall",
  "Massdrop",
  "Maximo",
  "Meccaudio",
  "Meze",
  "Microsoft",
  "MIRPH",
  "Mixcder",
  "MMR",
  "Modhouse",
  "Mofasest",
  "Monolith",
  "Monoprice",
  "Monster",
  "Montblanc",
  "Moondrop",
  "Motorola",
  "MUNITIO",
  "Muse",
  "Musical",
  "MyST",
  "Moritz",
  "Nan-6",
  "Mpow",
  "MrSpeakers",
  "MySphere",
  "NAD",
  "NarMoo",
  "NCM",
  "ND",
  "Nectar",
  "Neumann",
  "Neusonik",
  "NHT",
  "NICEHCK",
  "Nightjar",
  "Nintendo",
  "Nixon",
  "Noble",
  "Nocs",
  "Noontec",
  "Nothing",
  "Nuarl",
  "Nuforce",
  "Nura",
  "NVX",
  "oBravo",
  "Oladance",
  "Ollo",
  "Onkyo",
  "Oppo",
  "Ora",
  "ORB",
  "Oriolus",
  "Oriveti",
  "Ortofon",
  "Ostry",
  "Ourart",
  "Ovidius",
  "Palma",
  "Panasonic",
  "Paradigm",
  "Parrot",
  "PEARS",
  "Peerless",
  "Pendulumic",
  "Penon",
  "Pentaconn",
  "Padsmith",
  "Phiaton",
  "Philips",
  "Phonak",
  "Phonon",
  "Pioneer",
  "Plantronics",
  "Ploopy",
  "Plugged",
  "Plunge",
  "PNY",
  "PopClik",
  "Precide",
  "PSB",
  "PULA",
  "Puro",
  "qdc",
  "QCY",
  "QKZ",
  "Quad",
  "Qudelix",
  "QianYun",
  "Questyle",
  "RAAL",
  "Rikubuds",
  "RUNMUS",
  "Radius",
  "Raptgo",
  "Raycon",
  "Razer",
  "realme",
  "Redragon",
  "Redmi",
  "Reecho",
  "Remax",
  "RevoNext",
  "RBH",
  "RHA",
  "ROCCAT",
  "Rose",
  "RØDE",
  "Ritmix",
  "Rock",
  "Rode",
  "Sabbat",
  "Samson",
  "Samsung",
  "Sash",
  "SATOLEX",
  "Scosche",
  "Seahf",
  "Sendy",
  "SENSO",
  "SGOR",
  "Sennheiser",
  "Senfer",
  "Sansui",
  "Santa",
  "Seek",
  "Shanling",
  "Sineaptic",
  "Sleek",
  "Shokz",
  "Shozy",
  "Simphonio",
  "Shuoer",
  "Shure",
  "Simgot",
  "Sivga",
  "Skullcandy",
  "Smabat",
  "SMS",
  "Snab",
  "Soncie",
  "Sonic",
  "Soratune",
  "Softears",
  "Sonos",
  "Sony",
  "Somic",
  "Soranik",
  "Soul",
  "SoundMAGIC",
  "SOL",
  "SPC",
  "Spider",
  "Spirit",
  "Stax",
  "Stealthsonics",
  "Steelseries",
  "StereoPravda",
  "Sterling",
  "Superlux",
  "SWEEAR",
  "Swimbuds",
  "Symphonized",
  "SymphonyEars",
  "Syun",
  "T+A",
  "T-Peos",
  "Takstar",
  "Tanchjim",
  "Taobao",
  "TaoTronics",
  "TASCAM",
  "TDK",
  "Teac",
  "TCL",
  "Technics",
  "Tekfusion",
  "tekkusai",
  "Teknmotion",
  "TempoTec",
  "Thermaltake",
  "Thinksoud",
  "TENHZ",
  "Teufel",
  "TForce",
  "TGXear",
  "Tiandirenhe",
  "Timsok",
  "Tingker",
  "Tipsy",
  "TKZK",
  "Toneking",
  "Torque",
  "Toshiba",
  "TOZO",
  "Tralucent",
  "Tranya",
  "TREBLAB",
  "TRI",
  "TrueFree",
  "TY",
  "Tronsmart",
  "TWISTURA",
  "TFZ",
  "ThieAudio",
  "Thieaudio",
  "Thinksound",
  "Tripowin",
  "TRN",
  "Truthear",
  "UBSound",
  "Ucotech",
  "UFOEar",
  "UiiSii",
  "Ultrasone",
  "Umi",
  "Urbanears",
  "Urbanfun",
  "Valco",
  "Veedix",
  "Velodyne",
  "Vento",
  "Verum",
  "ViSang",
  "Vivo",
  "VJJB",
  "VSonic",
  "Warbler",
  "Warwick",
  "violator73",
  "W+G",
  "Walmart",
  "Westone",
  "Whizzer",
  "Wicked",
  "Willsound",
  "Woodees",
  "Wyze",
  "Xbox",
  "XFYRO",
  "Xiaomi",
  "XINHS",
  "XPG",
  "XSL",
  "XTZ",
  "Yamaha",
  "Yincrow",
  "Yinfu",
  "Yinyoo",
  "Ylife",
  "Yuin",
  "Yutai",
  "ZEMPIREAUDIO",
  "ZiiGaat",
  "Zipbuds",
  "ZMF",
  "Zoukbox",
].sort((a, b) => b.length - a.length); // Sort by length descending for greedy matching

/**
 * Vendor name aliases - maps alternate names to canonical names.
 * These map to the names used in the existing database to ensure consistent slugs.
 */
export const VENDOR_ALIASES: Record<string, string> = {
  // Spelling/capitalization normalization
  "B&W": "Bowers & Wilkins",
  "Bowers Wilkins": "Bowers & Wilkins",
  "Master Dynamic": "Master & Dynamic",
  "Thieaudio": "ThieAudio",
  "Hifiman": "HiFiMAN",
  "Earfun": "EarFun",
  "Dan Clark": "Dan Clark Audio",
  "V Moda": "V-MODA",
  "TANGZU": "Tangzu",
  "Blon": "BLON",
  "NF ACOUS": "NF Audio",
  "ISN AUDIO": "ISN Audio",
  "Audio-Technica": "Audio Technica",
  "KB EAR": "KBEAR",
  "Adam Audio": "Adam",

  // Map short/alternate names to canonical names in KNOWN_VENDORS
  "Campfire": "Campfire Audio",
  "Coolermaster": "Cooler Master",
  "IMR": "IMR Acoustics",
  "Letshuoer": "Shuoer",
  "Noble": "Noble Audio",
  "Open Audio": "OpenAudio",
  "PlusSound": "Plus Sound",
  "See Audio": "SeeAudio",
  "Simgot": "Simgot Audio",
  "LZ Audio": "LZ Hi-Fi Audio",

  // Company renames / rebrands
  "MrSpeakers": "Dan Clark Audio",
  "Tin Audio": "Tin HiFi",

  // Abbreviations → full name
  "B&O": "Bang & Olufsen",
  "MMR": "Metal Magic Research",

  // Short name → full name (full name has more data in DB)
  "Etymotic Research": "Etymotic",
  "Astro": "Astro Gaming",
  "Andover": "Andover Audio",
  "JLab": "JLab Audio",
  "Dita": "Dita Audio",
  "Modhouse": "Modhouse Audio",
  "Grell": "Grell Audio",
  "Rosson Audio": "Rosson Audio Design",
  "Warwick Audio": "Warwick Acoustics",

  // Full name → short name (short name has more data in DB)
  "Creative Labs": "Creative",
  "AFUL Acoustics": "AFUL",
  "Sivga Audio": "Sivga",
  "Shuoer Aoshida": "Shuoer",
  "Soul by Ludacris": "Soul",

  // Special character handling
  "T+A": "T+A",  // Ensure slug stays as "t_a" matching existing DB
};
